### ISSUE TITLE
Precinct numbers are mangled

### ISSUE THREAD

**Issue by jhalderm** [openelections/openelections-data-mi#2]
It looks like the precinct numbers got cut off or mangled during the data import.  Here's a snippet, where each line should refer to a unique precinct code (in the second column):

```
WASHTENAW,1,President,,REP,DONALD J. TRUMP,424
WASHTENAW,2,President,,REP,DONALD J. TRUMP,264
WASHTENAW,1,President,,REP,DONALD J. TRUMP,648
WASHTENAW,2,President,,REP,DONALD J. TRUMP,492
WASHTENAW,3,President,,REP,DONALD J. TRUMP,749
WASHTENAW,1,President,,REP,DONALD J. TRUMP,590
WASHTENAW,1,President,,REP,DONALD J. TRUMP,676
WASHTENAW,2,President,,REP,DONALD J. TRUMP,678
WASHTENAW,3,President,,REP,DONALD J. TRUMP,429

```

**Comment by nk9** [comment]
You can assign this to me.

**Comment by nk9** [comment]
I have revised the script to include the city in the precinct and the sort by county, precinct, office, district. But I have several questions.

1. I'm trying to figure out what to do with office 0, which is "POLL BOOK TOTALS (TOTAL VOTERS)". Since that total doesn't align with any of the individual races, it's not really useful. Here's what that looks like:

    county,precinct,office,district,party,candidate,votes
    ALCONA,ALCONA TOWNSHIP 1,Total,,,,725
    ALCONA,ALCONA TOWNSHIP 1,President,,NPA,TOM HOEFLING,0
    ALCONA,ALCONA TOWNSHIP 1,President,,NPA,MICHAEL A. MATUREN,0
    ALCONA,ALCONA TOWNSHIP 1,President,,NPA,MONICA MOOREHEAD,0
    ALCONA,ALCONA TOWNSHIP 1,President,,NPA,EVAN MCMULLIN,0
    ALCONA,ALCONA TOWNSHIP 1,President,,NPA,LAURENCE KOTLIKOFF,0
    ALCONA,ALCONA TOWNSHIP 1,President,,NPA,BEN HARTNELL,0
    ALCONA,ALCONA TOWNSHIP 1,President,,NPA,CHERUNDA FOX,0
    ALCONA,ALCONA TOWNSHIP 1,President,,GRN,JILL STEIN,2
    ALCONA,ALCONA TOWNSHIP 1,President,,DEM,HILLARY CLINTON,199
    ALCONA,ALCONA TOWNSHIP 1,President,,NLP,EMIDIO MIMI SOLTYSIK,0
    ALCONA,ALCONA TOWNSHIP 1,President,,REP,DONALD J. TRUMP,500
    ALCONA,ALCONA TOWNSHIP 1,President,,UST,DARRELL L. CASTLE,4
    ALCONA,ALCONA TOWNSHIP 1,President,,LIB,GARY JOHNSON,13
    ALCONA,ALCONA TOWNSHIP 1,U.S. House,1,GRN,ELLIS BOAL,2
    ALCONA,ALCONA TOWNSHIP 1,U.S. House,1,LIB,DIANE BOSTOW,14
    ALCONA,ALCONA TOWNSHIP 1,U.S. House,1,DEM,LON JOHNSON,237
    ALCONA,ALCONA TOWNSHIP 1,U.S. House,1,REP,JACK BERGMAN,448
    ALCONA,ALCONA TOWNSHIP 1,State House,106,DEM,ROBERT KENNEDY,215
    ALCONA,ALCONA TOWNSHIP 1,State House,106,REP,SUE ALLOR,476
    ALCONA,ALCONA TOWNSHIP 1,State House,106,LIB,DANA CARVER,15
    ALCONA,ALCONA TOWNSHIP 1,State House,106,NPA,JOHN CAPLIS,0

2. Also, how should I format these lines?

    ALCONA,{Statistical Adjustments} 9999,President,,NPA,MICHAEL A. MATUREN,16

3. The [PDFs for Wayne County](https://www.waynecounty.com/documents/clerk/16GPRDTR.pdf) (Detroit) have columns for straight party votes. I can't seem to find them in the statewide data, but I could easily be looking in the wrong place. But perhaps they're already included in the candidate votes?

4. The PDFs also include "precincts" labeled e.g. "Detroit AVCB _nnn_" for Detroit 1–172. (There are 490 non-AVCB precincts.) These are presumably the "Absentee Counting Board Results". In the statewide voter data, these come through as regular Detroit precincts, but labelled 900–1072. Do I need to label these to match the Wayne County PDFs? What the heck ARE these results?

**Comment by dwillis** [comment]
Good questions, @nk9. Here's what I think:

1. I think you can skip the poll book totals if you find them not useful.
2. The statistical adjustment is the difference between the official canvass results and the precinct results, so I would treat it as a pseudo-precinct (numbered 9999) and include them.
3. Straight party votes are included in the candidate votes, but are useful to have where they exist. In terms of parsing the statewide data you don't have to account for them, but it would be useful to make an issue noting that they exist for Wayne and pointing to the file.
4. So, the AVCB precincts are essentially set up to count absentee ballots outside the precinct structure (see [this](https://www.michigan.gov/documents/sos/VIII_Absent_Voter_County_Boards_265998_7.pdf) for details). You can keep the statewide IDs for our purposes and also note them in any Wayne County-specific issues you might file (like for number 3 above).

**Comment by nk9** [comment]
I did some more tweaking, including adding the ward to the precinct if present. Now our precincts look like this:

`CITY NAME {precinct_number} ["AVCB"] [WARD {ward_number}]`

I've run into another wrinkle, though. These two lines are both in the votes file:

    2016    GEN 8   02800   0   517513  50  74  2   57      665
    2016    GEN 8   02800   8   517513  50  74  2   57      644

Which result in this after being run through the present script:
    Macomb,WARREN CITY 57 WARD 2,State House,28,DEM,Patrick Green,665
    Macomb,WARREN CITY 57 WARD 2,State House,28,DEM,Patrick Green,644

As you can see, the only difference is in the "Status" column. Here's what [the readme](https://github.com/openelections/openelections-sources-mi/blob/master/2016/readme.txt) has to say about those:

```
0    Regular Term
8    Partial Term
```

Huh?? Two candidates, Antoine M. Davison and Patrick Green, have this problem. It's only for precincts in Macomb county, and it's not even for every one of those. But still, there are 35 instances of duplicates for each candidate.

Thoughts?

**Comment by dwillis** [comment]
I bet it's two elections - a regular election for a full term and a special election for a partial term to fill an open seat. https://ballotpedia.org/Patrick_Green

**Comment by nk9** [comment]
But the two elections happened at the same time, right? Both on 8 November. Does it just mean he was seated sooner because the special coincided with the general? Bizarre.

Anyway, what should I do about this? Filter out the "partial" lines?

**Comment by dwillis** [comment]
Correct; they happened on the same day, which does happen, although not often. It usually happens when a seat is vacated well before the term ends. There are two options: you can treat the special election as a separate file or you can change the district value by appending `Unexpired Term` to it. I think I'd go with the former.

**Comment by nk9** [comment]
Turns out, that wasn't the only special election which took place that day. Several other races were also technically specials. I've adapted the script. It now passes the verifier script. Now on to the other years!
